<a href="https://colab.research.google.com/github/Faisaleka21/Machine_Learning/blob/main/Perceptron%20and%20Multilayer%20Peceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [4]:
# Memuat dataset
df = pd.read_csv('https://raw.githubusercontent.com/febbisena/DataMining/refs/heads/main/dataset_tahu_berfomalin.csv')
df

,H2_MQ2(ppm),LPG_MQ2(ppm),CO_MQ2(ppm),Alcohol_MQ2(ppm),Propane_MQ2(ppm),CH4_MQ4(ppm),Smoke_MQ4(ppm),Temperature(C),label
0,1.6,0.8,3.7,1.3,1.1,0.7,0.0,1,0
1,1.6,0.8,3.7,1.3,1.1,0.7,0.0,1,0
2,1.6,0.8,3.7,1.3,1.1,0.7,0.0,1,0
3,1.6,0.8,3.7,1.3,1.1,0.7,0.0,1,0
4,1.6,0.8,3.7,1.3,1.1,0.7,0.0,1,0
...,...,...,...,...,...,...,...,...,...
44995,1.7,0.8,4.0,1.4,1.1,20.0,249.2,1,0
44996,1.7,0.8,4.0,1.4,1.1,20.0,249.2,1,0
44997,1.7,0.8,4.0,1.4,1.1,20.0,249.2,1,0
44998,1.8,0.9,4.2,1.5,1.2,20.2,255.9,1,0
44999,1.7,0.8,4.0,1.4,1.1,20.4,262.8,1,0

In [5]:
# Eksplorasi Data
df.shape

(45000, 9)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   H2_MQ2(ppm)       45000 non-null  float64
 1   LPG_MQ2(ppm)      45000 non-null  float64
 2   CO_MQ2(ppm)       45000 non-null  float64
 3   Alcohol_MQ2(ppm)  45000 non-null  float64
 4   Propane_MQ2(ppm)  45000 non-null  float64
 5   CH4_MQ4(ppm)      45000 non-null  float64
 6   Smoke_MQ4(ppm)    45000 non-null  float64
 7   Temperature(C)    45000 non-null  int64
 8   label             45000 non-null  int64
dtypes: float64(7), int64(2)
memory usage: 3.1 MB

In [7]:
df.isna().sum()

H2_MQ2(ppm)         0
LPG_MQ2(ppm)        0
CO_MQ2(ppm)         0
Alcohol_MQ2(ppm)    0
Propane_MQ2(ppm)    0
CH4_MQ4(ppm)        0
Smoke_MQ4(ppm)      0
Temperature(C)      0
label               0
dtype: int64

In [8]:
df.describe().T

                    count      mean        std  min  25%  50%  75%    max
H2_MQ2(ppm)       45000.0  1.515089   0.143856  1.0  1.4  1.5  1.6    1.9
LPG_MQ2(ppm)      45000.0  0.737707   0.076847  0.5  0.7  0.7  0.8    0.9
CO_MQ2(ppm)       45000.0  3.317580   0.432236  1.9  3.1  3.4  3.6    4.5
Alcohol_MQ2(ppm)  45000.0  1.189589   0.135163  0.7  1.1  1.2  1.3    1.5
Propane_MQ2(ppm)  45000.0  0.988322   0.094582  0.7  0.9  1.0  1.0    1.2
CH4_MQ4(ppm)      45000.0  3.169107   2.885546  0.7  1.8  2.3  3.2   20.4
Smoke_MQ4(ppm)    45000.0  5.753349  21.862526  0.0  0.2  0.4  1.0  262.8
Temperature(C)    45000.0  1.000000   0.000000  1.0  1.0  1.0  1.0    1.0
label             45000.0  0.485756   0.499803  0.0  0.0  0.0  1.0    1.0

In [9]:
# Pra-pemrosesan Data
df = df.drop(['Temperature(C)'], axis=1)

In [10]:
# Pembagian Fitur (X) dan Target (y)
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [11]:
X.tail()

,H2_MQ2(ppm),LPG_MQ2(ppm),CO_MQ2(ppm),Alcohol_MQ2(ppm),Propane_MQ2(ppm),CH4_MQ4(ppm),Smoke_MQ4(ppm)
44995,1.7,0.8,4.0,1.4,1.1,20.0,249.2
44996,1.7,0.8,4.0,1.4,1.1,20.0,249.2
44997,1.7,0.8,4.0,1.4,1.1,20.0,249.2
44998,1.8,0.9,4.2,1.5,1.2,20.2,255.9
44999,1.7,0.8,4.0,1.4,1.1,20.4,262.8

In [12]:
# Menampilkan 5 data terakhir dari target
y.tail()

44995    0
44996    0
44997    0
44998    0
44999    0
Name: label, dtype: int64

In [13]:
# Menghitung jumlah label (untuk melihat keseimbangan data)
print(y.value_counts())

label
0    23141
1    21859
Name: count, dtype: int64

In [14]:
# Membagi data menjadi data latih (train) dan data uji (test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Data train : ", len(X_train))
print("Data test  : ", len(X_test))

Data train :  36000
Data test  :  9000

In [15]:

# Normalisasi data menggunakan MinMaxScaler
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_test_scaled

array([[5.55555556e-01, 5.00000000e-01, 5.38461538e-01, ...,
        6.00000000e-01, 1.67512690e-01, 7.61035008e-03],
       [5.55555556e-01, 5.00000000e-01, 4.61538462e-01, ...,
        6.00000000e-01, 5.58375635e-02, 7.61035008e-04],
       [7.77777778e-01, 7.50000000e-01, 7.69230769e-01, ...,
        8.00000000e-01, 5.58375635e-01, 1.90258752e-01],
       ...,
       [5.55555556e-01, 5.00000000e-01, 5.00000000e-01, ...,
        6.00000000e-01, 1.52284264e-01, 6.46879756e-03],
       [5.55555556e-01, 5.00000000e-01, 5.00000000e-01, ...,
        6.00000000e-01, 9.64467005e-02, 1.90258752e-03],
       [7.77777778e-01, 7.50000000e-01, 7.30769231e-01, ...,
        8.00000000e-01, 4.06091371e-02, 3.80517504e-04]])

In [16]:
# Membangun arsitektur model Neural Network
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [17]:

# Menampilkan ringkasan arsitektur model
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,137 (12.25 KB)

 Trainable params: 3,137 (12.25 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:

# Kompilasi model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [19]:

# Pengaturan Early Stopping untuk mencegah overfitting
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [ ]:

# Melatih model (Training)
history = model.fit(
    X_train_scaled, y_train,
    validation_data=(X_test_scaled, y_test),
    epochs=1000,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

Epoch 1/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.5810 - loss: 0.6483 - val_accuracy: 0.5691 - val_loss: 0.6256
Epoch 2/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.6528 - loss: 0.5976 - val_accuracy: 0.7183 - val_loss: 0.5707
Epoch 3/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.6992 - loss: 0.5549 - val_accuracy: 0.7053 - val_loss: 0.5449
Epoch 4/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7084 - loss: 0.5349 - val_accuracy: 0.7292 - val_loss: 0.5296
Epoch 5/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7332 - loss: 0.5141 - val_accuracy: 0.7547 - val_loss: 0.5087
Epoch 6/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7552 - loss: 0.4916 - val_accuracy: 0.7827 - val_loss: 0.4881
Epoch 7/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7728 - loss: 0.4703 - val_accuracy: 0.7767 - val_loss: 0.4711
Epoch 8/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7878 - loss: 0.4543 - val_accuracy: 0.7894 - val_loss: 0.4573
Epoch 9/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7948 - loss: 0.4424 - val_accuracy: 0.7828 - val_loss: 0.4501
Epoch 10/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7986 - loss: 0.4351 - val_accuracy: 0.8031 - val_loss: 0.4303
Epoch 11/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8043 - loss: 0.4279 - val_accuracy: 0.8111 - val_loss: 0.4306
Epoch 12/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8100 - loss: 0.4185 - val_accuracy: 0.8233 - val_loss: 0.4224
Epoch 13/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8166 - loss: 0.4111 - val_accuracy: 0.8024 - val_loss: 0.4324
Epoch 14/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8201 - loss: 0.4015 - val_accuracy: 0.8203 - val_loss: 0.3924
Epoch 15/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8217 - loss: 0.3943 - val_accuracy: 0.8313 - val_loss: 0.3898
Epoch 16/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8253 - loss: 0.3897 - val_accuracy: 0.8324 - val_loss: 0.3783
Epoch 17/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8286 - loss: 0.3831 - val_accuracy: 0.8320 - val_loss: 0.3776
Epoch 18/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8284 - loss: 0.3806 - val_accuracy: 0.8042 - val_loss: 0.4090
Epoch 19/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8289 - loss: 0.3772 - val_accuracy: 0.8361 - val_loss: 0.3840
Epoch 20/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8282 - loss: 0.3734 - val_accuracy: 0.8270 - val_loss: 0.3790
Epoch 21/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8303 - loss: 0.3708 - val_accuracy: 0.8316 - val_loss: 0.3612
Epoch 22/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8319 - loss: 0.3675 - val_accuracy: 0.8259 - val_loss: 0.3721
Epoch 23/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8313 - loss: 0.3643 - val_accuracy: 0.8377 - val_loss: 0.3681
Epoch 24/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8333 - loss: 0.3606 - val_accuracy: 0.8300 - val_loss: 0.3694
Epoch 25/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8343 - loss: 0.3594 - val_accuracy: 0.8340 - val_loss: 0.3636
Epoch 26/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8336 - loss: 0.3570 - val_accuracy: 0.8398 - val_loss: 0.3529
Epoch 27/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8347 - loss: 0.3551 - val_accuracy: 0.8424 - val_loss: 0.3568
Epoch 28/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8340 - loss: 0.3533 - val_accuracy: 0.8396 - val_loss: 0.3486
Epoch 29/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8350 - loss: 0.3509 - val_accuracy: 0.8351 - val_loss: 0.3560
Epoch 30/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8405 - loss: 0.3456 - val_accuracy: 0.8399 - val_loss: 0.3461
Epoch 31/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8357 - loss: 0.3465 - val_accuracy: 0.8330 - val_loss: 0.3422
Epoch 32/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8393 - loss: 0.3432 - val_accuracy: 0.8371 - val_loss: 0.3528
Epoch 33/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8395 - loss: 0.3388 - val_accuracy: 0.8386 - val_loss: 0.3406
Epoch 34/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8432 - loss: 0.3392 - val_accuracy: 0.8307 - val_loss: 0.3560
Epoch 35/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8436 - loss: 0.3368 - val_accuracy: 0.8337 - val_loss: 0.3591
Epoch 36/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8446 - loss: 0.3333 - val_accuracy: 0.8457 - val_loss: 0.3315
Epoch 37/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8466 - loss: 0.3320 - val_accuracy: 0.8553 - val_loss: 0.3299
Epoch 38/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8448 - loss: 0.3320 - val_accuracy: 0.8480 - val_loss: 0.3321
Epoch 39/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8492 - loss: 0.3276 - val_accuracy: 0.8448 - val_loss: 0.3331
Epoch 40/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8474 - loss: 0.3290 - val_accuracy: 0.8471 - val_loss: 0.3287
Epoch 41/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8493 - loss: 0.3268 - val_accuracy: 0.8350 - val_loss: 0.3570
Epoch 42/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8485 - loss: 0.3261 - val_accuracy: 0.8509 - val_loss: 0.3238
Epoch 43/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8510 - loss: 0.3211 - val_accuracy: 0.8531 - val_loss: 0.3231
Epoch 44/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8499 - loss: 0.3226 - val_accuracy: 0.8486 - val_loss: 0.3333
Epoch 45/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8521 - loss: 0.3218 - val_accuracy: 0.8502 - val_loss: 0.3260
Epoch 46/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8497 - loss: 0.3228 - val_accuracy: 0.8419 - val_loss: 0.3376
Epoch 47/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8495 - loss: 0.3222 - val_accuracy: 0.8487 - val_loss: 0.3233
Epoch 48/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8528 - loss: 0.3191 - val_accuracy: 0.8507 - val_loss: 0.3215
Epoch 49/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8522 - loss: 0.3181 - val_accuracy: 0.8561 - val_loss: 0.3224
Epoch 50/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8536 - loss: 0.3158 - val_accuracy: 0.8499 - val_loss: 0.3261
Epoch 51/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8541 - loss: 0.3156 - val_accuracy: 0.8682 - val_loss: 0.3087
Epoch 52/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8523 - loss: 0.3174 - val_accuracy: 0.8533 - val_loss: 0.3179
Epoch 53/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8554 - loss: 0.3148 - val_accuracy: 0.8490 - val_loss: 0.3160
Epoch 54/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8541 - loss: 0.3134 - val_accuracy: 0.8577 - val_loss: 0.3135
Epoch 55/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8536 - loss: 0.3134 - val_accuracy: 0.8468 - val_loss: 0.3159
Epoch 56/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8562 - loss: 0.3135 - val_accuracy: 0.8591 - val_loss: 0.3126
Epoch 57/1000
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8562 - loss: 0.3119 - val_accuracy: 0.8633 - val_loss: 0.3179
Epoch 58/1000
  54/1125 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8682 - loss: 0.3044

In [ ]:
# Visualisasi Loss dan Accuracy per Epoch
plt.figure(figsize=(6, 8))

In [ ]:
# Grafik Loss
plt.subplot(2, 1, 1)
plt.plot(history.history['loss'], label='Loss (Training)')
plt.plot(history.history['val_loss'], label='Loss (Validation)')
plt.title('Loss per Epoch')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

In [ ]:

# Grafik Accuracy
plt.subplot(2, 1, 2)
plt.plot(history.history['accuracy'], label='Accuracy (Training)')
plt.plot(history.history['val_accuracy'], label='Accuracy (Validation)')
plt.title('Accuracy per Epoch')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.show()

In [ ]:

# Melakukan prediksi pada data uji
y_pred = (model.predict(X_test_scaled) > 0.5).astype("int32")

In [ ]:

# Membuat Confusion Matrix
class_names = y.unique()
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6, 4))
sns.set(font_scale=1.2)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

In [ ]:
# Menampilkan Classification Report
class_report = classification_report(y_test, y_pred, digits=4)
print("Classification Report :\n", class_report)

In [ ]:

# Menampilkan Accuracy Score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy Score: {accuracy * 100:.2f}%")

In [ ]:

# Membuat DataFrame untuk hasil pengujian
test_df = pd.DataFrame(X_test, columns=X.columns)
test_df['Actual Class'] = y_test.values
test_df['Predicted Class'] = y_pred

test_df

In [ ]:

# Membuat perbandingan jumlah kelas Aktual vs Prediksi
comparison_df = test_df.groupby('Actual Class').size().to_frame('Actual')
comparison_df['Predicted'] = test_df.groupby('Predicted Class').size()

# Mengisi nilai kosong dengan 0 dan mengubah tipe data ke integer
comparison_df.fillna(0, inplace=True)
comparison_df = comparison_df.astype(int)

# Visualisasi Bar Chart Perbandingan Aktual vs Prediksi
ax = comparison_df.plot(kind='bar', figsize=(8, 8), color=['skyblue', 'green'])

# Menambahkan label angka di atas bar
ax.bar_label(ax.containers[0], fmt='%d', padding=3)
ax.bar_label(ax.containers[1], fmt='%d', padding=3)

plt.title('Actual vs Predicted Class Counts')
plt.xlabel('Class')
plt.ylabel('Count')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

In [ ]:

# Menyimpan hasil prediksi ke file Excel
test_df.to_excel('MLP_Data Test & Prediction.xlsx', index=False)

In [ ]:

# Menyimpan model yang sudah dilatih
model.save('Model MLP.h5')